spring.datasource.url=jdbc:postgresql://localhost:5432/SpringJDBCDemo
spring.datasource.username=postgres
spring.datasource.password=2yeargoal
spring.datasource.driver-class-name=org.postgresql.Driver


